name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Usar Node.js 20, como recomienda Azure

      # Paso 3: Instalar dependencias
      - name: Install Dependencies
        run: npm install

      # Paso 4: Construir la aplicación Angular
      - name: Build Angular App
        run: npm run build -- --configuration production

      # Paso 5: Desplegar en Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_SEA_058B0020F }}
          app_location: "/"  # Directorio raíz del código fuente
          output_location: "dist/frontend"  # Directorio de salida (compilado)
          api_location: ""  # Dejar vacío si no hay API
          action: "upload"  # Acción de despliegue obligatoria
